config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'lessons/form' => 'lessons#form'
  get 'lessons/register' => 'lessons#register'
  get 'lessons/hello' => 'lessons#hello'

  resources :users do
    resources :plan_items, only:[:index]
  end
  resources :plan_items do
    resources :participations, only: [:create, :destroy] do
      patch :cancel, on: :member
    end
  end

  resource :session, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participation.rb
class Participation < ApplicationRecord
	belongs_to :user
	belongs_to :plan_item
end

app/models/plan_item.rb
# == Schema Information
#
# Table name: plan_items
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  description :text             not null
#  starts_at   :datetime         not null
#  ends_at     :datetime         not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class PlanItem < ApplicationRecord
  before_save do
    if starts_at_date_part && starts_at_time_part
      self.starts_at = "#{starts_at_date_part} #{starts_at_time_part}"
    end

    if ends_at_date_part && ends_at_time_part
      self.ends_at = "#{ends_at_date_part} #{ends_at_time_part}"
    end
  end
  
  belongs_to :user 
  has_many :participations, dependent: :destroy
  has_many :participants, through: :participations, source: :user
  paginates_per 4

  attr_writer :starts_at_date_part, :starts_at_time_part,
    :ends_at_date_part, :ends_at_time_part

  def starts_at_date_part
    @starts_at_date_part ||= starts_at&.strftime('%Y-%m-%d')
  end

  def starts_at_time_part
    @starts_at_time_part ||= starts_at&.strftime('%H:%M')
  end

  def ends_at_date_part
    @ends_at_date_part ||= ends_at&.strftime('%Y-%m-%d')
  end

  def ends_at_time_part
    @ends_at_time_part ||= ends_at&.strftime('%H:%M')
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, presence: {on: :create}, confirmation: true
  validates :name, uniqueness: {case_senstive: true}
  attr_accessor :password, :password_confirmation
  has_many :plan_items, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :participating_events, through: :participations, source: :plan_item
  def password=(val)
    if val.present?
      self.hashed_password =BCrypt::Password.create(val)
    end
    @password = val
  end

  private
  def self.authenticate(full_name, password)
    user = find_by(full_name: full_name)
    if user && user.hashed_password.present? &&
        BCrypt::Password.new(user.hashed_password) == password
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  class Forbidden < StandardError; end
  private 
  def current_user
  	@current_user ||= User.find_by(id: session[:user_id])
  end 

  def login_required
  	raise Forbidden unless current_user
  end 

  helper_method :current_user
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def form
  end

  def register
    @user_name = params[:user][:name]
  end

  def hello
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
	def create
		plan_item = PlanItem.find(params[:plan_item_id])
		plan_item.participations.create!(user: current_user)
		flash.notice = '申し込みを受付ました'
		redirect_to [current_user, :plan_items] 
	end 

	def destroy
		plan_item = PlanItem.find(params[:plan_item_id])
		user = User.find_by(id: current_user.id)
		plan_item.participants.destroy(user)
		flash.notice = '#{plan_item.name}の申し込みをキャンセルしました'
		redirect_to [current_user, :plan_items]
	end 
end

app/controllers/plan_items_controller.rb
class PlanItemsController < ApplicationController
  before_action :login_required
  def index
    if params[:user_id] && params[:user_id].to_i == current_user.id
      @plan_items = current_user.participating_events.
        order(:starts_at).page(params[:page])
    else
      @plan_items = PlanItem.order(:starts_at).page(params[:page])
    end
  end

  def show
    @plan_item = PlanItem.find(params[:id])
  end

  def new
    @plan_item = PlanItem.new
    time0 = Time.current.beginning_of_hour
    @plan_item.starts_at = time0.advance(hours: 1)
    @plan_item.ends_at = time0.advance(hours: 2)
  end

  def edit
    @plan_item = current_user.plan_items.find(params[:id])
  end

  def create
    @plan_item = PlanItem.new(plan_item_params)
    @plan_item.user = current_user
    if @plan_item.save
      @plan_item.participants << current_user
      redirect_to [current_user, :plan_items], notice: '予定を追加しました。'
    else
      render "new"
    end
  end

  def update
    plan_item = PlanItem.find(params[:id])
    plan_item.update_attributes(plan_item_params)

    redirect_to :plan_items, notice: '予定を更新しました。'
  end

  def destroy
    plan_item = current_user.plan_items.find(params[:id])
    plan_item.destroy!
    redirect_to :plan_items, notice: '予定を削除しました。'
  end

  private
  def plan_item_params
    params[:plan_item].permit(
      :name, :description,
      :starts_at_date_part, :starts_at_time_part,
      :ends_at_date_part, :ends_at_time_part
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user= User.authenticate(params[:full_name], params[:password])
    if user
      session[:user_id] = user.id
    else
      flash.alert = "名前とパスワードが一致しません"
    end
    redirect_to :root
  end

  def destroy
  	session.delete(:user_id)
  	redirect_to :root
  end 
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, except:[:new, :create]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(params[:user])
    if @user.save
      redirect_to @user
    else
      render "edit"
    end
  end


  def create
    @user = User.new(params[:user])
    if @user.save
      flash.notice = "created"
      session[:user_id] = @user.id
      redirect_to users_path
    else
      flash.alert = "not created"
      render "new"
    end
  end

  def destroy
  end

end

app/helpers/application_helper.rb
# -*- frozen_string_literal: true -*-

module ApplicationHelper
  def format_duration(item)
    w1 = format_wday(item.starts_at)
    w2 = format_wday(item.ends_at)

    s = String.new('')
    if item.starts_at.year == Time.current.year
      s << item.starts_at.strftime("%-m月%-d日 (#{w1}) %H:%M")
    else
      s << item.starts_at.strftime("%Y年%-m月%-d日 (#{w1}) %H:%M")
    end

    s << ' ～ '

    if item.ends_at.to_date == item.starts_at.to_date
      s << item.ends_at.strftime('%H:%M')
    elsif item.ends_at.year == item.starts_at.year
      s << item.ends_at.strftime("%-m月%-d日 (#{w2}) %H:%M")
    else
      s << item.ends_at.strftime("%Y年%-m月%-d日 (#{w2}) %H:%M")
    end
  end

  def format_datetime(datetime)
    w = format_wday(datetime)
    datetime.strftime("%Y年%-m月%-d日 (#{w}) %H:%M")
  end

  def format_wday(datetime)
    %w(日 月 火 水 木 金 土)[datetime.wday]
  end
end

app/views/layouts/_flash_messages.html.erb
<% if flash.notice.present? %>
  <div class='alert alert-success'>
    <%= flash.notice %>
  </div>
<% end %>
<% if flash.alert.present? %>
  <div class='alert alert-danger'>
    <%= flash.alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>PicoPlanner</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('pico_planner.ico') %>
    <%= favicon_link_tag('clock256.png', rel: 'apple-touch-icon') %>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-toggleable-md  navbar-light bg-faded">
        <div class="navbar-header">
          <%= link_to 'PicoPlanner', :root , class:"navbar-brand"%>
        </div>
        <div class="collapse navbar-collapse">
          <div class="nav navbar-nav">
            <p class="navbar-text">
              <% if current_user %>
                welcome<%= current_user.name %> | <%= link_to "logout", :session, method: :delete, data:{confirm: "Are you shure?"} %>
              <% else %>
                <%= link_to "新規登録", new_user_path , class:"navbar-link"%>
              <% end %>
            </p>
          </div>
        </div>
      </nav>
      <main>
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </main>
      <footer>
        &copy; 2016 Oiax Inc.
    </footer>
    </div>
  </body>
</html>

app/views/lessons/_content.html.erb
<p class='card-text'>Hello, world!</p>

app/views/lessons/form.html.erb
<form action='/lessons/register' method='get'>
  <div class='form-group'>
    <label for='user-name'>ユーザー名</label>
    <input type='text' name='user[name]' id='user-name' class='form-control'>
  </div>
  <div class='form-group'>
    <label for='user-password'>パスワード</label>
    <input type='password' name='user[password]' id='user-password'
      class='form-control'>
  </div>
  <div class='form-group'>
    <label for='user-remarks'>備考</label>
    <textarea name='user[remarks]' id='user-remarks'
      class='form-control' rows='4'></textarea>
  </div>
  <div class='form-group'>
    <input type='submit' value='登録' class='btn btn-primary'>
  </div>
</form>

app/views/lessons/hello.html.erb
<div class='card'>
  <div class='card-block'>
    <%= render 'content' %>
  </div>
</div>

app/views/lessons/register.html.erb
user_name = "<%= @user_name %>"

app/views/plan_items/_datetime_picker.html.erb
<div class='row'>
  <div class='col-xs-12 col-md-7'>
    <div class='input-group date-picker'>
      <%= f.text_field "#{attr_name}_date_part",
        class: 'form-control', required: true %>
      <span class='input-group-addon'><i class='fa fa-calendar'></i></span>
    </div>
  </div>
  <div class='col-xs-12 col-md-5'>
    <div class='hidden-md-up' style='margin-top: 0.5rem'></div>
    <div class='input-group time-picker'>
      <%= f.text_field "#{attr_name}_time_part",
        class: 'form-control', required: true %>
      <span class='input-group-addon'><i class='fa fa-clock-o'></i></span>
    </div>
  </div>
</div>

app/views/plan_items/_delete_confirmation.html.erb
<div class='modal' id='delete-confirmation-<%= item.id %>'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal'>
          <i class='fa fa-times'></i>
        </button>
        <h4 class='modal-title'>予定を削除します</h4>
      </div>
      <div class='modal-body'>
        <p>予定「<%= item.name %>」を削除してもよろしいですか。</p>
        <p>削除した予定を元に戻すことはできません。</p>
      </div>
      <div class='modal-footer'>
        <%= link_to 'はい', item, method: :delete, class: 'btn btn-primary' %>
        <a class='btn btn-secondary' data-dismiss='modal'>
          いいえ
        </a>
      </div>
    </div>
  </div>
</div>

app/views/plan_items/_fields.html.erb
<div class='form-group'>
  <%= f.label :name, '件名' %>
  <%= f.text_field :name, class: 'form-control', required: true %>
</div>
<div class='form-group'>
  <%= f.label :description, '説明' %>
  <%= f.text_area :description, class: 'form-control', rows: 4 %>
</div>
<div class='form-group'>
  <%= f.label :starts_at, '開始日時' %>
  <%= render 'datetime_picker', f: f, attr_name: :starts_at %>
</div>
<div class='form-group'>
  <%= f.label :ends_at, '終了日時' %>
  <%= render 'datetime_picker', f: f, attr_name: :ends_at %>
</div>

app/views/plan_items/_md_toolbar.html.erb
<% if item.user == current_user %>
  <%= link_to [ :edit, item ], class: 'btn btn-secondary btn-sm' do %>
    <i class='fa fa-pencil-square'></i> 変更
  <% end %>
  <%= link_to "#delete-confirmation-#{item.id}", class: 'btn btn-secondary btn-sm', data: { toggle: 'modal'} do %>
    <i class='fa fa-trash'></i> 削除
  <% end %>
<% else %>
	<% if participation = item.participations.find_by(user_id: current_user.id) %>
		<%= link_to [item, participation], method: :delete, class: 'btn btn-secondary btn-sm' do %>
		  	<i class="fa fa-pencil-square"></i>キャンセルする
		<% end %>
	<% else %> 
		<%= link_to [item, :participations], method: :post,  class: 'btn btn-secondary btn-sm' do %>
  			<i class="fa fa-pencil-square"></i>申し込む
 		 <% end %>
  	<% end %>
<% end %>

app/views/plan_items/_xs_toolbar.html.erb
<%= link_to [ :edit, item ] do %>
  <i class='fa fa-pencil-square fa-lg'></i>
<% end %>

<%= link_to "#delete-confirmation-#{item.id}",
  data: { toggle: 'modal'} do %>
  <i class='fa fa-trash fa-lg'></i>
<% end %>

app/views/plan_items/edit.html.erb
<%= form_for @plan_item do |f| %>
  <%= render 'fields', f: f %>
  <div class='form-group'>
    <%= f.submit '更新', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/plan_items/index.html.erb
<% @plan_items.each do |item| %>
  <%= render 'delete_confirmation', item: item %>
<% end %>
<div class='container-fluid plan-items'>
  <% if current_user %>
    <h2> welcome <%= current_user.name %>さん</h2>
    <span><%= paginate @plan_items, :theme => 'twitter-bootstrap-4' %></span>
    <% @plan_items.each do |item| %>
      <div class='row'>
        <div class='col-xs-8 col-md-4'>
          <span class='plan-item-name'><%= link_to item.name, item %></span>
        </div>
        <div class='col-xs-4 hidden-md-up text-xs-right toolbar'>
          <%= render 'xs_toolbar', item: item %>
        </div>
        <div class='col-xs-12 col-md-5'>
          <span class='plan-item-description'>
            <% item.description.split("\n").each do |line| %>
              <%= line %><br>
            <% end %>
          </span>
        </div>
        <div class='col-md-3 hidden-sm-down text-xs-right toolbar'>
          <%= render 'md_toolbar', item: item %>
        </div>
        <div class='col-xs-12'>
          <span class='plan-item-duration'><%= format_duration(item) %></span>
        </div>
      </div>
    <% end %>
  <% else %>
    <h1>ログイン</h1>
    <%= form_tag :session  do%>
      <table>
        <tr>
          <td sytle="text-align: right">フルネーム:</td>
          <td> <%= text_field_tag "full_name", "", style:"width:120px" %> </td>
        </tr>
        <tr>
          <td sytle="text-align: right">パスワード:</td>
          <td> <%= password_field_tag "password", "", style:"width:120px" %> </td>
        </tr>
        <tr>
          <td colspan="2" style="text-align: center">
            <%= submit_tag "login" %></td>
        </tr>
      </table>
    <% end %>
    <h2> <%= link_to "新規登録", new_user_path %></h2>
  <% end %>
</div>

app/views/plan_items/new.html.erb
<%= form_for @plan_item do |f| %>
  <%= render 'fields', f: f %>
  <div class='form-group'>
    <%= f.submit '追加', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/plan_items/show.html.erb
<%= render 'delete_confirmation', item: @plan_item %>

<div class='container-fluid plan-item'>
  <div class='row'>
    <div class='col-xs-12 hidden-md-up text-xs-right toolbar'>
      <%= link_to :plan_items do %>
        <i class='fa fa-list fa-lg'></i>
      <% end %>
      <%= render 'xs_toolbar', item: @plan_item %>
    </div>
    <div class='col-md-12 hidden-sm-down text-md-right toolbar'>
      <%= link_to :plan_items, class: 'btn btn-secondary btn-sm' do %>
        <i class='fa fa-list'></i> 予定表へ戻る
      <% end %>
      <%= render 'md_toolbar', item: @plan_item %>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-12 col-md-4 bg-info text-md-right'>件名</div>
    <div class='col-xs-12 col-md-8'><%= @plan_item.name %></div>
  </div>
  <div class='row'>
    <div class='col-xs-12 col-md-4 bg-info text-md-right'>説明</div>
    <div class='col-xs-12 col-md-8'>
      <% @plan_item.description.split("\n").each do |line| %>
        <%= line %><br>
      <% end %>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-12 col-md-4 bg-info text-md-right'>開始日時</div>
    <div class='col-xs-12 col-md-8'>
      <%= format_datetime @plan_item.starts_at %>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-12 col-md-4 bg-info text-md-right'>終了日時</div>
    <div class='col-xs-12 col-md-8'>
      <%= format_datetime @plan_item.ends_at %>
    </div>
  </div>
</div>

app/views/top/index.html.erb
<% if current_user %>
  <div class='list-group'>
    <%= link_to :plan_items, class: 'list-group-item' do %>
      <i class='fa fa-list'></i> イベント一覧
    <% end %>
    <%= link_to [current_user, :plan_items], class: 'list-group-item' do %>
      <i class='fa fa-list'></i> 参加予定イベント
      <% end %>
    <%= link_to :new_plan_item, class: 'list-group-item' do %>
      <i class='fa fa-plus'></i> 予定の追加
    <% end %>
  <% else %>
    <div class="card">
      <div class="card-block">
        <h2>ログイン</h2>
        <%= form_tag :session  do%>
          <div class="form-group">
            <label for="full_name">フルネーム:</label>
            <%= text_field_tag "full_name", "",class:"form-control"%>
          </div>
          <div class="form-group">
            <label for="password">パスワード:</label>
            <%= password_field_tag "password", "" , class:"form-control"%>
          </div>
          <%= submit_tag "login", class:"btn btn-primary" %></td>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>hello</h1>
<%= @users.each do |user| %>
  <h1><%= user.name %></h1>
<% end %>

app/views/users/new.html.erb
<div class="card">
  <div class="card-block">
    <h1>新規登録/New</h1>
    <%= form_for @user do |form| %>
      <%= form.label :full_name %>
      <div class="form-group">
        <%= form.text_field :full_name, style:"width:180px",class:"form-control" %>
      </div>
      <%= form.label :name %>
      <div class="form-group">
        <%= form.text_field :name, style:"width:180px", class:"form-control" %>
      </div>
      <%= form.label :password %>
      <div class="form-group">
        <%= form.password_field :password, style:"width:180px", class:"form-control" %>
      </div>
      <%= form.label :password_confirmation %>
      <div class="form-group">
        <%= form.password_field :password_confirmation, style:"width:180px", class:"form-control" %>
      </div>
      <p><%= form.submit class:"btn btn-primary" %></p>
    <% end %>
  </div>
</div>